#!/usr/bin/env python3
from localStoragePy import localStorage as lc
from pprint import pprint
from json import loads
def test():
    print("[0/5] Initialize localStorage.")
    localStorage = lc("testing.jkelol111.me")
    print("[1/5] setItem type str.")
    localStorage.setItem("testing_string", "Hello World")
    print("[2/5] setItem type str but it is JSON.")
    localStorage.setItem("testing_string_json", '{"testing": "Hello World"}')
    print("[3/5] getItem type str.")
    print(localStorage.getItem("testing_string"))
    print("[4/5] getItem type str but it is JSON.")
    pprint(loads(localStorage.getItem("testing_string_json"))["testing"])
    print("[5/5] clear all.")
    localStorage.clear()
if __name__ == "__main__":
    print("Starting testing for localStoragePy...")
    test()
    print("Everything passed!")
